language: java
dist: trusty
jdk:
  - openjdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - xyz0330@aliyun.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
# need to encrypt those sensitive env variables
env:
  global:
  - DOCKER_USERNAME=zhangxue6
  - DOCKER_PASSWORD=zxy123456
  #- AWS_ACCESS_KEY=AKIA4JVP6YTE2LLEIMYX
  #- AWS_SECRET_KEY=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
  - GITHUB_TOKEN=80ff73b88dd20b81008eea74dde342fb841db986
before_install:
- gem install travis
- sudo curl -k -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
- sudo chmod +x /usr/local/bin/ecs-cli
- export BUILD_NAME=chapter10-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
- export CONTAINER_IP=3.17.6.117
- export PLATFORM_TEST_NAME="chapter10-platform-tests"
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
- sh travis_scripts/deploy_to_amazon_ecs.sh
# sh travis_scripts/trigger_platform_tests.sh
