language: java
dist: trusty
jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - xyz0330@aliyun.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
env:
  global:
  - secure: XZpUQOa/cuOcg2gbNzT9kcjGi6baXMnr4iF7oFSkupYVRfZyerv/o3tx1Dx/IcvvZxbvGZ9aQRWqwwlmG1iZa2zIJ1o5Gz6+2xgrQko8yvo6OCfcjz9kiHlgaSGmz2LHvX4hqj0E/I+gibIsDplKPc4jb5UeFPl7EBkWLs8EKkzxCPJDGj66NLAkiOeLQPl5iuHO1pfjRa1u/sgtdCU+CUR2Gtx3Ymw2MS6XgMX4Gcxol+fhRYl+f2x0dp6ns+a3JVHqbI4ZO5HXHwkAzPdxezqJ8Nz+JT8NQGFxTanB7nt7FMmiVAcwful0Y4XmNhEkJM9+8XkvuRRpYDv95GGIQLV35ARfcTv0CdRfc88ZUq3jEeQnBkG1WycXCZnvaV9AOeHpzzbFUdRhf23WS37qTa7IPQ6CE0nUQKqpAmcHvQRe/z9ZSHUDtJGBCVHBRh308FwlfOMb5x08GsE3N+F5q1r9CEo2aalTlWkmwwXtAHaM9JtdmwaCK3RXAADU3HxtT0azRd05Or1iI1QZpScrJYdqqZXlL/ZvGH9iAmJjeEat+OgphadEDSOHGeKZD3sns189qbVkCLxJLkCbANSfNjuGFC+LvB+eK5iN65979SUsKtGOGpImppvSj7mP1UerreDpRaJhr5xDNhXSeyUahWG6Nu+rk8A3jHLDDlI2k9k=
  - secure: ZMtbn7S7U+5L6AE6d7o9sK+qGidbcxikaMdi8Exk6EfTRVZADKxZgNyjEm7hckgF2z9eydU1x8BNpH9DIrYWHuDVIKiIbCN2w8lVyZhVW1Fng8BG3sV6NngLwWuc1QZEYNbggxWwxuTWJVZK6fg3AGwnPy7OW92ox15TS1XJmXWl0+I33FuhwP8uLAtd75iVFA+quACdGmR1Ig7qN76QeDwqLl2MyTt0HI5MYY/u+qr7h+RKOeX/JVMzgcX+RF7G8YRJoksVX1omTfjWGSYSkz9kjrL4G8OGiM5UQitVnuJOL0+FJVjXkrbfwOY4aBOII4eRW2w+N9iAPiMszw48B0Dk8nHwy1T6x7giok+eBXhvqcwstw+ZEqzrbLu2Ko3y+H78DuyCgo4uUW34XgOosGMce6BUpueKDlZEu0Z9O/QTVYGU4eaLrgs43bn9L9YhOnPbOJRtXzOgaGtv8xdjtjr3FdDbwrwHyZQARn1lsWzuvv08a+oqB5WRmnP8t6rQPI1vjlC6+jjeGCYzVRjVtTeiZ4NII26UFZUgYX7KOqi5WL8Kb405WuuFV+rimsWSS647YXMKMcSGjzO/sWgrHvKhUy8CaDLPR5YVfjnJlqTdXCKQHqcMEKzQSrJTSK218sh2/6mtbzskGj1JG/neWDsYJIhEf+d2EzW0gc8VQ7g=
  - secure: Qt7LJSWagekg4/dqkOnC1YXmwlC7nlnjY2SW/Vhs7pru6kVVSV9aMPlhzNCYx1vGPDW7+JuMmsC342Ss0Xrrs39gsIeHQPajFtZsBfXzrlA9ov5NIWLJIycB83rsz5dUXhNEHRC87VKP9BTnUr0btSSS1ysYlnaXw1V6chPgYi/iGAAaoDZZtb0jFNoD0yw210ntdPudNAaKMVLSExA/OIwCK0iSIxXcJsA55VJzLTEfJzwbvK2WkhwUxG2PEGQ+56f2BrEwk9II1NzLjR4zWf6zCm6RxhAxoVkYtYWMSlRADtOGWZ4jBwTVHnufO/Ah/wM18XMrdbLMr302XSucio8zuV4M3KkKZoDBmjX4mh2FjpVMkoI1bkpqLDdzoU4jpIPCAgw5LzHVXxY5+l6I/wQhPU4MTyBqkEiCSBwoZEtDDL2Flci0mEuVwN+DZN595a6lGvqe0L2BJI+678zGXt1VF+op4bveWwdHMptQyHy84HgA+eg/D5s36l054HtUHt6p857n8BOCA9w27PhF++I6iiumxt2wveefxRMJXTbR3hYJc6k3rdaNQ1Kjv8HhsUfhEJJlA2l6dTtXXyV5KPOVheRhktZX3K3U9Idcu2o4Q/2bW7sS7u/3RwDgijaD03M1aVlwbf7Opz177vRsT6R7oCiSi5N02s6P3v3Q6/w=
  - secure: fi171rbqgKDFv2oJb2DhbYWYDhX0O9Bq/QF1yh+Sgv20CJn/KKZJKkJAeSKQ449BPxuuHnLAXDibp+zymvKFOT+9+pkuTwYhfAnaXAqBvBfBOGrn9waG/UDDTmN5PKwj144l8FsRt0J82LsyHhSahZriDNiuRuukmlfL+Yt/95vVS9Qr6S7Yr5LJM0QV+Ait2c59cu5klsXi/7Tc3WMdVvc/ooz9SrMQQe1zpL+ZqLiyB1Z+eXNbXi2nCCmX5+vMHzeonFA6PqMmz7KYXn9CUNKRK+0CzlT42U3z0x/odexCmoMdwTJ9z3a3sMog6pfuOYZzlrQEMduYPMdWPp0GU4EMZre4TqEoK5d8FbSTpnbzwCBbizxDjrMwOUVG41hlhg572ETiRPWgZDdiE5DU363pWSgts4hbfQib9bbGg7h16EHloT/Xct4xNaflBL0j05TVT94kSTHUy/UH9ovjTM7t4BdnnMG2E9ggKcRSqLlY4teVxIx/3INtoUne3/x4ilez8lWXV7JIE94EOhpSonbD+Z+/CV/BonnegLv79y11Zn/MJtmqnQ5syY60ervOJDcUp26qCqk4pecKck4qX42yFcMEh8LWyzzPMqJ4RaiSi2zoYLNcO9eR9IZdIM9+ckw+hE5SmDGpWOJez0ubaLm5mW5RS2PPT4Dm35rOAFQ=
  - secure: LLHQ/z3RzQcLhdgsuN3SlF7zOCyRzh0bTohh4y+LmeGcjbNayNWNae2nJJvD5P9ucxIXk+3H8IwMEOIetc9VMycAMA1S9qRvi2Bv7R18C17+YasLXuyEEGkcrR5ANVYCvvDlAboGrnL7Oa9Vvb+GlW8OizR0+0jaEcE6EGxg68eWhwmvp+NPQJbNVSWO6w3K56kKcvOD7r0nk1UbURRQ9RLOn+M6xjRK8dxigNBm8Rznx9BtN9MClDTl0b7QkBq2Zv0a+ftVwUaBAH8sMZRjXa/FRyoYRy/utzyQA1IrZsRnffCgbVZYzcxG8Ghbm1cIVldMLfq2yXDcHuIVfY6dXbmDmfv6QW0OwcfjUmMCo+897Y3K2MkutcK2DPgHjl/bqH+e4mhmyoFMJ4zaIvlI4vc8RzcfKe24bP0SigPAVyZrw4lxKZNx1HjqMbf5qoNYkMNNzj8Zu3Q7Aw4UkFYcjpyAd0zB+4S5rpk7efk4zma5B04IBFpybixpEFxdWAPkn/5BpASVmcGh1VEG6qEHX1a27aT4Pe8M7tL3V6lRqvjCjpQos8p/rkpv+vMAtS9Jnky1SSMzeI3N1OpEogApgv+/pbI37jDm20a2YWEHZdR0HghUiTsoex8TJWO/fwefamfwK1su9C6xka/wylc3ZIZaciumLmRbJW2i8aRQL2I=
before_install:
- gem install travis
- sudo curl -k -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
- sudo chmod +x /usr/local/bin/ecs-cli
- export BUILD_NAME=chapter10-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
- export CONTAINER_IP=13.58.55.221
- export PLATFORM_TEST_NAME="chapter10-platform-tests"
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
- sh travis_scripts/deploy_to_amazon_ecs.sh
