eurekaserver:
   image:   zhangxue6/tmx-eurekasvr:${BUILD_NAME}
   mem_limit: 1073741824
   ports:
       - "8761:8761"

configserver:
    image: zhangxue6/tmx-confsvr:${BUILD_NAME}
    #mem_limit: 1073741824
    mem_limit: 1000000000
    ports:
       - "8888:8888"
    links:
       - "eurekaserver:eurekaserver"
    environment:
       EUREKASERVER_PORT: 8761
       EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
       ENCRYPT_KEY:       "IMSYMMETRIC"

zuulserver:
    image: zhangxue6/tmx-zuulsvr:${BUILD_NAME}
    mem_limit: 1073741824
    ports:
      - "5555:5555"
    links:
      - "eurekaserver:eurekaserver"
      - "configserver:configserver"
    environment:
      PROFILE: "default"
      SERVER_PORT: "5555"
      CONFIGSERVER_PORT: 8888
      EUREKASERVER_PORT: 8761
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"

licensingservice:
    image: zhangxue6/tmx-licensing-service:${BUILD_NAME}
    mem_limit: 1073741824
    ports:
      - "8080:8080"
    links:
      - "configserver:configserver"
      - "eurekaserver:eurekaserver"
      - "zuulserver:zuulserver"
      - "kafkaserver:kafkaserver"
      - "authenticationservice:authenticationservice"
    environment:
      PROFILE: "aws-dev"
      SERVER_PORT: "8080"
      ES_PORT:           9200
      DATABASE_PORT:     5432
      CONFIGSERVER_PORT: 8888
      EUREKASERVER_PORT: 8761
      AUTHSERVER_PORT:   8091
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      KAFKASERVER_URI: "kafkaserver"
      ZKSERVER_URI: "kafkaserver"
      AUTHSERVER_URI:   "http://authenticationservice:8901/auth/user"
      ENCRYPT_KEY:       "IMSYMMETRIC"

authenticationservice:
    image: zhangxue6/tmx-authentication-service:${BUILD_NAME}
    mem_limit: 1073741824
    ports:
      - "8901:8901"
    links:
      - "configserver:configserver"
      - "eurekaserver:eurekaserver"
      - "zuulserver:zuulserver"
    environment:
      PROFILE: "aws-dev"
      SERVER_PORT: "8901"
      DATABASE_PORT:     5432
      CONFIGSERVER_PORT: 8888
      EUREKASERVER_PORT: 8761
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      ENCRYPT_KEY:       "IMSYMMETRIC"

organizationservice:
    image: zhangxue6/tmx-organization-service:${BUILD_NAME}
    mem_limit: 1073741824
    ports:
      - "8085:8085"
    links:
      - "configserver:configserver"
      - "eurekaserver:eurekaserver"
      - "zuulserver:zuulserver"
      - "kafkaserver:kafkaserver"
      - "authenticationservice:authenticationservice"
    environment:
      PROFILE: "aws-dev"
      SERVER_PORT: "8085"
      DATABASE_PORT:     5432
      CONFIGSERVER_PORT: 8888
      EUREKASERVER_PORT: 8761
      AUTHSERVER_PORT:   8091
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      KAFKASERVER_URI: "kafkaserver"
      ZKSERVER_URI: "kafkaserver"
      AUTHSERVER_URI:   "http://authenticationservice:8901/auth/user"
      ENCRYPT_KEY:       "IMSYMMETRIC"

kafkaserver:
    image: spotify/kafka
    mem_limit: 1073741824
    ports:
      - 2181:2181
      - 9092:9092